language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJYEPIAQD4Q4RQD4A
  secret_access_key:
    secure: vcIEIwEbj36XqZrI4G8nXmApCLeFD4e//GXX9vtGBG/ZG/JNW3JuUTBqDOJpRQIm/qxSSnER9irnSDpyRrji5meRnPp3qakpoLJbjJmukkFZxsVsYRJ1EH+c+qxJhGaPaMF408nFVMPVhLxUB57+DBzl+FEXSy+TIfVGApjp01L5zm5WCHtm64k68R9wDEQIODqhP803NWc/pOjiFmGRf22AoRjdDfskvjJcZTaJYP5HZhnjgRbcbtQNMtJpLcHiGQKPHqE/pdzBO8xA0bH7H9Mq2GCa0S4MRiO+4yJc4lIODFmqGjxWz5AOh7w0+UUKKxH2UkLY2h7MOM0ZSAHUIwtLh51XYUUGdgtMuhdwhWFqAU8mOMWwzPApwcoP0fxnHGZA2F9NNcAsKFmXh2RAb5pKqQlSw3ebICGDfm9gPO6oUkcpFPqGN18YiZZnRaT5ksGJ/pIE8xy9GlcRVZFzgE6NyvNNFrHMfMl4gQB5vM0bU5+yYSvxs6jzu/XVeIRJRFVMbPtl/5YwutgsfQzC4C9JA2JoZkbFYPVctTV1WsFZRlpJ7PfE6BVVLojTFpmWvxO8k1WhwFex8YP9EBMzWrkgH/Dr6m93ESaPeSWP9vymO1DNpDuT8heBwd6M7mMsUsXEZ3/Sb/QZ+MkeAJzgmkNZuG0KG2tsO0kUjVJyx5E=
  bucket: darrenshaw.org
  local-dir: _site
  acl: public_read
  on:
    repo: shawdm/darrenshaw_org
    branch: deployment/enable_travis_ci
