language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJADHXHVQHZUC2VRA
  secret_access_key:
    secure: OI9edVVMfhBh/qprsSEFtJKFXedYhBt4/uExvMwJjUkrEtXASnGMfi1wBIkUfzbG5DQpBDdLDQpFzYOtSOmUR7KBCRXjPVu4QTUlRYxHcfF6XTi9XV/9m25RfdfRWqWp9IUkYLdM5N6LhubeYu4B6v371jE3BKtSjJYACDacnk75VYStvH3GHwF7EyfSaH39ADKku34OiS+cWdfF6mN+DQdjShQCHU7riUvHAeJDqb7iUzOzC4p0/O+DYJCmwVTvJzGdC3h/tNkNoWH7W6ztmNGrtMatqyfzzMggYVn4m/T9D0eKu35gr4DYhAvheYhhrstM5ulVrqQIrme8NlQpyptlp4m+9u63fUXAws09tmYwiB/uUlU7CsghNpoNFhi+fMcHNhC2J1VpBQkNTF7cEEtGnJBI3Q8LC+DUpM+4/w8HqNnPRKzZQS/z76j7jpv2Ps0kW/wqW8q07KMVKLTRcG9owYOSjTj7hR7YY/GdCbkRiG+5OyQomlZuVTVqEiuv3ZYkj6ED+lAujGxKcnIFInqZqa0Lt3+33yFgPnJc9uU3a2DjLkMwUQybBRR6UfzaNcJIZXA4Bq7GPcLr5TIFuefXwLojzWki64VZAnfRu0G3r2i8cjQyp5sC1BwaMwGzGkU3+RRxePvIjUFt0kQNHPAjtCq+X1dCzvDWNp8NGwE=
  bucket: darrenshaw.org
  local-dir: _site
  on:
    repo: shawdm/darrenshaw_org
    branch: deployment/enable_travis_ci
