# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: darrenshaw.org
email: shawdm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! Darren Shaw here, a portrait photographer living and working around
  Southampton in Hampshire. I mainly shoot beauty and editorial work. As well
  as digital, I enjoy working with older film cameras and love soft, naturally
  lit black and white images. I’m always looking to meet new models, makeup
  artists and stylists. So if you’re interested in working together, get in
  touch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://darrenshaw.org" # the base hostname & protocol for your site
twitter_username: shawdm
github_username:  shawdm
paginate: 100

# Build settings
markdown: kramdown
